package main

import (
	"fmt"
	"time"
)

type ServerCommand struct {
	Name string `short:"n" long:"name" description:"Name of this server." default:"autogenerated"`
}

var serverCommand ServerCommand

func (x *ServerCommand) Execute(args []string) error {
	return runServer(connect(globalOptions, "server"))
}

func init() {
	parser.AddCommand("server",
		"Run the local server agent.",
		"",
		&serverCommand)
}

func runServer(conn Connection) error {
	for {
		message := <-conn.In

		fmt.Println("Message received: ", message.Contents)

		// wait a small amount of time so that the return message isn't lost
		time.Sleep(5 * time.Millisecond)

		// send it back
		conn.Out <- message
	}

	return nil
}
